# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "Dockerfile"
      - ".dockerignore"
      - "fly.toml"

permissions:
  contents: read
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v6
      - name: Write config to file
        env:
          SERVER_CONFIG: ${{ secrets.SERVER_CONFIG }}
        run: |
          echo "$SERVER_CONFIG" > config.toml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --app ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
